/**
 * Demo catalog — ~80 clearly-labelled sample products.
 *
 * Everything here is honest prototype data: fictional demo suppliers, no real
 * ratings/reviews/stock/discount claims. Numeric prices are in OMR. Colours are
 * expanded from the taxonomy so this file stays compact and every swatch stays
 * consistent with its filter.
 *
 * The array order is the deterministic "Recommended" ordering. `addedAt` is
 * assigned deterministically (a pseudo-spread of dates) purely so that
 * "Recently added" sorting is meaningful — it is not a real inventory event.
 */

import type {
  CategorySlug,
  ColorId,
  ColorOption,
  Dimensions,
  DemoSupplier,
  Localized,
  MaterialId,
  Product,
  RoomType,
  StockStatus,
  StyleTag,
} from "./types";
import { colorSwatches } from "./taxonomy";

interface RawProduct {
  slug: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  category: CategorySlug;
  subcategory?: string;
  price: number;
  supplier: DemoSupplier;
  stockStatus: StockStatus;
  dimensions: Dimensions;
  materials: MaterialId[];
  colors: ColorId[];
  styleTags: StyleTag[];
  roomTypes: RoomType[];
  features: Localized[];
  customizable: boolean;
  customizationOptions?: string[];
}

function colorOptions(ids: ColorId[]): ColorOption[] {
  return ids.map((id) => ({ id, label: colorSwatches[id].label, hex: colorSwatches[id].hex }));
}

const BASE_DAY = Date.UTC(2026, 7, 5); // 2026-08-05
const DAY = 86_400_000;

/** Expand raw demo rows into full, typed products. */
function build(rows: RawProduct[]): Product[] {
  return rows.map((r, i) => ({
    ...r,
    id: r.slug,
    currency: "OMR" as const,
    isDemo: true as const,
    colors: colorOptions(r.colors),
    featuredRank: i,
    // Deterministic pseudo-spread so "newest" differs from "recommended".
    addedAt: new Date(BASE_DAY - ((i * 37) % 400) * DAY).toISOString().slice(0, 10),
  }));
}

const STUDIO: DemoSupplier = "Athathi Studio Collection";
const DEMO: DemoSupplier = "Athathi Demo Supplier";
const LAB: DemoSupplier = "Demo Furniture Lab";

const rows: RawProduct[] = [
  // ── Sofas ────────────────────────────────────────────────────────────────
  {
    slug: "luna-modular-sofa",
    name: "Luna Modular Sofa",
    nameAr: "كنبة لونا المعيارية",
    description: "A deep, low modular sofa in soft bouclé — built to be reconfigured as the room changes.",
    descriptionAr: "كنبة معيارية منخفضة وعميقة بقماش البوكليه الناعم، تُعاد ترتيبها مع تغيّر الغرفة.",
    category: "sofas",
    subcategory: "modular",
    price: 320,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 268, depthCm: 98, heightCm: 72, seatHeightCm: 43, seatDepthCm: 62 },
    materials: ["boucle", "oak"],
    colors: ["cream", "beige", "sage"],
    styleTags: ["warm-modern", "contemporary"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Reconfigurable modules", ar: "وحدات قابلة لإعادة الترتيب" },
      { en: "Feather-blend cushions", ar: "وسائد بمزيج الريش" },
    ],
    customizable: true,
    customizationOptions: ["fabric", "configuration"],
  },
  {
    slug: "noor-three-seat-sofa",
    name: "Noor Three-Seat Sofa",
    nameAr: "كنبة نور بثلاثة مقاعد",
    description: "A clean three-seater with a tailored linen cover and slim solid-oak legs.",
    descriptionAr: "كنبة بثلاثة مقاعد بتصميم أنيق وغطاء كتان مشدود وأرجل رفيعة من خشب البلوط.",
    category: "sofas",
    price: 265,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 214, depthCm: 92, heightCm: 84, seatHeightCm: 46, seatDepthCm: 58 },
    materials: ["linen", "oak"],
    colors: ["beige", "taupe", "grey"],
    styleTags: ["warm-modern", "scandinavian"],
    roomTypes: ["living-room"],
    features: [
      { en: "Removable, washable covers", ar: "أغطية قابلة للفك والغسل" },
      { en: "High-resilience foam", ar: "إسفنج عالي المرونة" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "salma-curved-sofa",
    name: "Salma Curved Sofa",
    nameAr: "كنبة سلمى المنحنية",
    description: "A sculptural curved two-and-a-half seater that softens an open living space.",
    descriptionAr: "كنبة منحنية نحتية بمقعدين ونصف تضفي نعومة على المساحات المفتوحة.",
    category: "sofas",
    price: 340,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 232, depthCm: 100, heightCm: 74, seatHeightCm: 44 },
    materials: ["velvet", "ash"],
    colors: ["sand", "olive", "rust"],
    styleTags: ["contemporary", "classic-modern"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Curved sculptural frame", ar: "هيكل منحني نحتي" },
      { en: "Made to order", ar: "يُصنع حسب الطلب" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "rami-l-shape-sectional",
    name: "Rami L-Shape Sectional",
    nameAr: "كنبة رامي زاوية على شكل L",
    description: "A generous L-shaped sectional for family rooms, with a reversible chaise.",
    descriptionAr: "كنبة زاوية واسعة على شكل L لغرف العائلة، مع شيزلونج قابل للعكس.",
    category: "sofas",
    subcategory: "sectional",
    price: 445,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 288, depthCm: 168, heightCm: 82, seatHeightCm: 45, seatDepthCm: 64 },
    materials: ["linen", "boucle"],
    colors: ["grey", "beige", "charcoal"],
    styleTags: ["modern", "contemporary"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Reversible chaise", ar: "شيزلونج قابل للعكس" },
      { en: "Family-scale seating", ar: "مقاعد بحجم عائلي" },
    ],
    customizable: true,
    customizationOptions: ["fabric", "orientation"],
  },
  {
    slug: "hana-loveseat",
    name: "Hana Loveseat",
    nameAr: "كنبة هنا لمقعدين",
    description: "A compact two-seater for smaller rooms, with plush bouclé and rounded arms.",
    descriptionAr: "كنبة صغيرة لمقعدين للغرف الأصغر، بقماش بوكليه وثير وأذرع دائرية.",
    category: "sofas",
    price: 198,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 158, depthCm: 88, heightCm: 78, seatHeightCm: 45 },
    materials: ["boucle", "oak"],
    colors: ["cream", "ivory", "sage"],
    styleTags: ["scandinavian", "minimal"],
    roomTypes: ["living-room", "bedroom"],
    features: [
      { en: "Space-saving footprint", ar: "مساحة صغيرة موفّرة" },
      { en: "Rounded arms", ar: "أذرع دائرية" },
    ],
    customizable: false,
  },
  {
    slug: "yusuf-leather-sofa",
    name: "Yusuf Leather Sofa",
    nameAr: "كنبة يوسف الجلدية",
    description: "A mid-century three-seater in full-grain leather that warms with age.",
    descriptionAr: "كنبة بثلاثة مقاعد بطراز منتصف القرن من الجلد الطبيعي الذي يزداد جمالاً مع الوقت.",
    category: "sofas",
    price: 520,
    supplier: LAB,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 220, depthCm: 94, heightCm: 80, seatHeightCm: 46 },
    materials: ["leather", "walnut"],
    colors: ["walnut", "charcoal", "rust"],
    styleTags: ["mid-century", "classic-modern"],
    roomTypes: ["living-room", "office"],
    features: [
      { en: "Full-grain leather", ar: "جلد طبيعي كامل الحبيبات" },
      { en: "Solid walnut frame", ar: "هيكل من خشب الجوز الصلب" },
    ],
    customizable: true,
    customizationOptions: ["leather"],
  },
  {
    slug: "dana-boucle-sofa",
    name: "Dana Bouclé Sofa",
    nameAr: "كنبة دانة بوكليه",
    description: "A rounded, cloud-like three-seater in textured bouclé for a relaxed living room.",
    descriptionAr: "كنبة دائرية غيمية بثلاثة مقاعد من قماش البوكليه لغرفة معيشة مريحة.",
    category: "sofas",
    price: 355,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 226, depthCm: 102, heightCm: 70, seatHeightCm: 42 },
    materials: ["boucle"],
    colors: ["ivory", "cream", "beige"],
    styleTags: ["warm-modern", "contemporary"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Soft rounded silhouette", ar: "شكل دائري ناعم" },
      { en: "Deep, loungeable seat", ar: "مقعد عميق مريح للاسترخاء" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "tariq-daybed-sofa",
    name: "Tariq Daybed Sofa",
    nameAr: "كنبة طارق سرير نهاري",
    description: "A low, versatile daybed that works as a sofa, a lounge, or majlis seating.",
    descriptionAr: "سرير نهاري منخفض متعدد الاستخدامات يصلح ككنبة أو جلسة استرخاء أو مجلس.",
    category: "sofas",
    price: 240,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 200, depthCm: 90, heightCm: 60, seatHeightCm: 38 },
    materials: ["cotton", "ash"],
    colors: ["sand", "taupe", "olive"],
    styleTags: ["boho", "japandi"],
    roomTypes: ["living-room", "majlis", "outdoor"],
    features: [
      { en: "Multi-use low profile", ar: "تصميم منخفض متعدد الاستخدام" },
      { en: "Bolster cushions included", ar: "وسائد إسطوانية مرفقة" },
    ],
    customizable: false,
  },
  {
    slug: "maha-floor-sofa",
    name: "Maha Floor Majlis Sofa",
    nameAr: "جلسة مها الأرضية للمجلس",
    description: "A modular floor-seating set for a modern majlis — firm base cushions and back rests.",
    descriptionAr: "طقم جلسة أرضية معياري لمجلس عصري، بوسائد قاعدة ثابتة ومساند ظهر.",
    category: "sofas",
    subcategory: "majlis",
    price: 285,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 300, depthCm: 80, heightCm: 45, seatHeightCm: 18 },
    materials: ["linen", "cotton"],
    colors: ["beige", "sand", "charcoal"],
    styleTags: ["contemporary", "boho"],
    roomTypes: ["majlis", "living-room"],
    features: [
      { en: "Modern majlis floor seating", ar: "جلسة مجلس أرضية عصرية" },
      { en: "Firm supportive cushions", ar: "وسائد ثابتة وداعمة" },
    ],
    customizable: true,
    customizationOptions: ["fabric", "length"],
  },

  // ── Chairs ───────────────────────────────────────────────────────────────
  {
    slug: "rima-accent-chair",
    name: "Rima Accent Chair",
    nameAr: "كرسي ريما الجانبي",
    description: "A sculptural lounge chair in oak and linen — comfortable enough to read in for hours.",
    descriptionAr: "كرسي استرخاء نحتي من خشب البلوط والكتان، مريح للقراءة لساعات.",
    category: "chairs",
    subcategory: "accent",
    price: 145,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 72, depthCm: 78, heightCm: 82, seatHeightCm: 42, seatDepthCm: 52 },
    materials: ["linen", "oak"],
    colors: ["beige", "sage", "taupe"],
    styleTags: ["japandi", "warm-modern"],
    roomTypes: ["living-room", "bedroom", "office"],
    features: [
      { en: "Solid oak frame", ar: "هيكل من خشب البلوط الصلب" },
      { en: "Ergonomic recline", ar: "استلقاء مريح للجسم" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "lina-lounge-chair",
    name: "Lina Lounge Chair",
    nameAr: "كرسي لينا للاسترخاء",
    description: "A deep bouclé lounge chair with a swivel base for a relaxed reading corner.",
    descriptionAr: "كرسي استرخاء عميق من البوكليه بقاعدة دوّارة لركن قراءة مريح.",
    category: "chairs",
    subcategory: "lounge",
    price: 175,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 80, depthCm: 82, heightCm: 78, seatHeightCm: 40 },
    materials: ["boucle", "steel"],
    colors: ["cream", "ivory", "grey"],
    styleTags: ["contemporary", "warm-modern"],
    roomTypes: ["living-room", "office"],
    features: [
      { en: "360° swivel base", ar: "قاعدة دوّارة 360°" },
      { en: "Textured bouclé", ar: "قماش بوكليه بملمس بارز" },
    ],
    customizable: false,
  },
  {
    slug: "omar-dining-chair",
    name: "Omar Dining Chair",
    nameAr: "كرسي عمر للطعام",
    description: "A solid-ash dining chair with a woven rattan back — sold as a pair.",
    descriptionAr: "كرسي طعام من خشب الدردار الصلب بظهر روطان منسوج، يُباع كزوج.",
    category: "chairs",
    subcategory: "dining",
    price: 96,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 48, depthCm: 54, heightCm: 82, seatHeightCm: 46 },
    materials: ["ash", "rattan"],
    colors: ["oak", "walnut"],
    styleTags: ["scandinavian", "japandi"],
    roomTypes: ["dining-room", "office"],
    features: [
      { en: "Sold as a pair", ar: "يُباع كزوج" },
      { en: "Handwoven rattan back", ar: "ظهر روطان منسوج يدوياً" },
    ],
    customizable: false,
  },
  {
    slug: "sara-armchair",
    name: "Sara Armchair",
    nameAr: "كرسي سارة بذراعين",
    description: "A softly upholstered armchair with rounded arms and a compact footprint.",
    descriptionAr: "كرسي منجّد ناعم بأذرع دائرية ومساحة صغيرة.",
    category: "chairs",
    subcategory: "accent",
    price: 128,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 74, depthCm: 76, heightCm: 80, seatHeightCm: 44 },
    materials: ["velvet", "oak"],
    colors: ["olive", "rust", "navy"],
    styleTags: ["mid-century", "classic-modern"],
    roomTypes: ["living-room", "bedroom"],
    features: [
      { en: "Velvet upholstery", ar: "تنجيد مخملي" },
      { en: "Compact footprint", ar: "مساحة صغيرة" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "kareem-office-chair",
    name: "Kareem Office Chair",
    nameAr: "كرسي كريم المكتبي",
    description: "A quietly modern task chair in leather and matte steel — support without the gamer look.",
    descriptionAr: "كرسي عمل عصري هادئ من الجلد والفولاذ المطفي، دعم دون مظهر ألعاب.",
    category: "chairs",
    subcategory: "office",
    price: 165,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 62, depthCm: 62, heightCm: 96, seatHeightCm: 48 },
    materials: ["leather", "steel"],
    colors: ["charcoal", "walnut", "black"],
    styleTags: ["modern", "industrial"],
    roomTypes: ["office"],
    features: [
      { en: "Height adjustable", ar: "ارتفاع قابل للتعديل" },
      { en: "Matte steel base", ar: "قاعدة فولاذية مطفية" },
    ],
    customizable: false,
  },
  {
    slug: "tala-bar-stool",
    name: "Tala Bar Stool",
    nameAr: "كرسي تالا العالي",
    description: "A counter-height stool in solid oak with a subtly contoured seat.",
    descriptionAr: "كرسي عالٍ بارتفاع الكاونتر من خشب البلوط الصلب بمقعد مُشكّل بلطف.",
    category: "chairs",
    subcategory: "stool",
    price: 78,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 44, depthCm: 44, heightCm: 92, seatHeightCm: 66 },
    materials: ["oak"],
    colors: ["oak", "walnut", "charcoal"],
    styleTags: ["scandinavian", "minimal"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Counter height", ar: "بارتفاع الكاونتر" },
      { en: "Contoured seat", ar: "مقعد مُشكّل" },
    ],
    customizable: false,
  },
  {
    slug: "ghala-reading-chair",
    name: "Ghala Reading Chair",
    nameAr: "كرسي غلا للقراءة",
    description: "A high-backed wing chair in wool with a matching footstool.",
    descriptionAr: "كرسي بظهر عالٍ من الصوف مع مسند قدمين مطابق.",
    category: "chairs",
    subcategory: "lounge",
    price: 210,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 82, depthCm: 86, heightCm: 104, seatHeightCm: 44 },
    materials: ["wool", "walnut"],
    colors: ["sage", "grey", "navy"],
    styleTags: ["classic-modern", "warm-modern"],
    roomTypes: ["living-room", "bedroom", "office"],
    features: [
      { en: "Includes footstool", ar: "يتضمن مسند قدمين" },
      { en: "Supportive high back", ar: "ظهر عالٍ داعم" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "sami-folding-chair",
    name: "Sami Folding Chair",
    nameAr: "كرسي سامي القابل للطي",
    description: "A teak folding chair for the balcony or dining table — sold as a pair.",
    descriptionAr: "كرسي قابل للطي من خشب الساج للشرفة أو طاولة الطعام، يُباع كزوج.",
    category: "chairs",
    subcategory: "dining",
    price: 88,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 46, depthCm: 52, heightCm: 86, seatHeightCm: 45 },
    materials: ["teak"],
    colors: ["oak", "walnut"],
    styleTags: ["scandinavian", "minimal"],
    roomTypes: ["dining-room", "outdoor"],
    features: [
      { en: "Folds flat for storage", ar: "يُطوى بالكامل للتخزين" },
      { en: "Weather-friendly teak", ar: "خشب ساج يتحمّل الأجواء" },
    ],
    customizable: false,
  },

  // ── Coffee tables ────────────────────────────────────────────────────────
  {
    slug: "noura-coffee-table",
    name: "Noura Coffee Table",
    nameAr: "طاولة نورة للقهوة",
    description: "A solid-walnut coffee table with a softly rounded edge and a lower shelf.",
    descriptionAr: "طاولة قهوة من خشب الجوز الصلب بحافة دائرية ناعمة ورف سفلي.",
    category: "coffee-tables",
    price: 69,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 110, depthCm: 60, heightCm: 38 },
    materials: ["walnut"],
    colors: ["walnut", "oak"],
    styleTags: ["warm-modern", "mid-century"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Solid walnut top", ar: "سطح من خشب الجوز الصلب" },
      { en: "Lower display shelf", ar: "رف عرض سفلي" },
    ],
    customizable: false,
  },
  {
    slug: "mira-travertine-coffee-table",
    name: "Mira Travertine Coffee Table",
    nameAr: "طاولة ميرا الترافرتين للقهوة",
    description: "A round travertine coffee table with a warm, natural veining.",
    descriptionAr: "طاولة قهوة دائرية من الترافرتين بعروق طبيعية دافئة.",
    category: "coffee-tables",
    price: 135,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 90, depthCm: 90, heightCm: 34, diameterCm: 90 },
    materials: ["travertine"],
    colors: ["cream", "sand", "taupe"],
    styleTags: ["contemporary", "minimal"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Natural travertine", ar: "ترافرتين طبيعي" },
      { en: "Round, edge-safe form", ar: "شكل دائري آمن الحواف" },
    ],
    customizable: false,
  },
  {
    slug: "faris-nesting-tables",
    name: "Faris Nesting Tables",
    nameAr: "طاولات فارس المتداخلة",
    description: "A pair of nesting coffee tables in oak and powder-coated steel.",
    descriptionAr: "زوج من طاولات القهوة المتداخلة من خشب البلوط والفولاذ المطلي.",
    category: "coffee-tables",
    subcategory: "nesting",
    price: 92,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 70, depthCm: 46, heightCm: 42 },
    materials: ["oak", "steel"],
    colors: ["oak", "charcoal", "sage"],
    styleTags: ["scandinavian", "industrial"],
    roomTypes: ["living-room"],
    features: [
      { en: "Set of two", ar: "طقم من قطعتين" },
      { en: "Tuck away when not needed", ar: "تُخزّن بسهولة عند عدم الحاجة" },
    ],
    customizable: false,
  },
  {
    slug: "hind-drum-coffee-table",
    name: "Hind Drum Coffee Table",
    nameAr: "طاولة هند الأسطوانية للقهوة",
    description: "A sculptural drum-shaped table in warm oak veneer — a quiet centrepiece.",
    descriptionAr: "طاولة أسطوانية نحتية بقشرة خشب بلوط دافئة، قطعة مركزية هادئة.",
    category: "coffee-tables",
    price: 84,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 80, depthCm: 80, heightCm: 36, diameterCm: 80 },
    materials: ["oak"],
    colors: ["oak", "cream", "walnut"],
    styleTags: ["japandi", "warm-modern"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Drum silhouette", ar: "شكل أسطواني" },
      { en: "Hidden storage nook", ar: "مساحة تخزين مخفية" },
    ],
    customizable: false,
  },
  {
    slug: "adam-glass-coffee-table",
    name: "Adam Glass Coffee Table",
    nameAr: "طاولة آدم الزجاجية للقهوة",
    description: "A slim tempered-glass top on a blackened steel frame for a light, open look.",
    descriptionAr: "سطح زجاجي مقسّى رفيع على هيكل فولاذي أسود لمظهر خفيف ومفتوح.",
    category: "coffee-tables",
    price: 110,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 120, depthCm: 60, heightCm: 40 },
    materials: ["glass", "steel"],
    colors: ["black", "charcoal"],
    styleTags: ["modern", "industrial"],
    roomTypes: ["living-room"],
    features: [
      { en: "Tempered glass top", ar: "سطح زجاجي مقسّى" },
      { en: "Visually light", ar: "مظهر خفيف بصرياً" },
    ],
    customizable: false,
  },
  {
    slug: "boho-carved-coffee-table",
    name: "Wafa Carved Coffee Table",
    nameAr: "طاولة وفا المنحوتة للقهوة",
    description: "A low carved-wood table with a handcrafted texture and rustic warmth.",
    descriptionAr: "طاولة منخفضة من الخشب المنحوت بملمس مصنوع يدوياً ودفء ريفي.",
    category: "coffee-tables",
    price: 96,
    supplier: DEMO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 100, depthCm: 100, heightCm: 32 },
    materials: ["teak"],
    colors: ["walnut", "oak", "sand"],
    styleTags: ["boho", "classic-modern"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Hand-carved detail", ar: "تفاصيل منحوتة يدوياً" },
      { en: "Solid teak", ar: "خشب ساج صلب" },
    ],
    customizable: false,
  },

  // ── Side tables ──────────────────────────────────────────────────────────
  {
    slug: "sila-side-table",
    name: "Sila Side Table",
    nameAr: "طاولة سيلا الجانبية",
    description: "A petite travertine side table that pairs with any sofa.",
    descriptionAr: "طاولة جانبية صغيرة من الترافرتين تناسب أي كنبة.",
    category: "side-tables",
    price: 38,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 40, depthCm: 40, heightCm: 50, diameterCm: 40 },
    materials: ["travertine"],
    colors: ["cream", "sand", "taupe"],
    styleTags: ["minimal", "contemporary"],
    roomTypes: ["living-room", "bedroom", "majlis"],
    features: [
      { en: "Solid stone top", ar: "سطح حجري صلب" },
      { en: "Sofa-height surface", ar: "سطح بارتفاع الكنبة" },
    ],
    customizable: false,
  },
  {
    slug: "jood-nightstand",
    name: "Jood Nightstand",
    nameAr: "كومودينو جود",
    description: "A two-drawer oak nightstand with a soft-close runner and a cable notch.",
    descriptionAr: "كومودينو من خشب البلوط بدرجين وإغلاق ناعم وفتحة للأسلاك.",
    category: "side-tables",
    subcategory: "nightstand",
    price: 52,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 46, depthCm: 40, heightCm: 52 },
    materials: ["oak"],
    colors: ["oak", "walnut", "white"],
    styleTags: ["scandinavian", "warm-modern"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Soft-close drawers", ar: "أدراج بإغلاق ناعم" },
      { en: "Cable management notch", ar: "فتحة لتنظيم الأسلاك" },
    ],
    customizable: false,
  },
  {
    slug: "reem-c-table",
    name: "Reem C-Table",
    nameAr: "طاولة ريم على شكل C",
    description: "A slide-under C-table for a laptop or coffee beside the sofa.",
    descriptionAr: "طاولة على شكل C تنزلق تحت الكنبة للحاسوب أو القهوة.",
    category: "side-tables",
    price: 34,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 40, depthCm: 36, heightCm: 62 },
    materials: ["metal", "oak"],
    colors: ["charcoal", "oak", "brass"],
    styleTags: ["modern", "industrial"],
    roomTypes: ["living-room", "office"],
    features: [
      { en: "Slides under the sofa", ar: "تنزلق تحت الكنبة" },
      { en: "Laptop-friendly height", ar: "ارتفاع مناسب للحاسوب" },
    ],
    customizable: false,
  },
  {
    slug: "aya-pedestal-table",
    name: "Aya Pedestal Table",
    nameAr: "طاولة آية بقاعدة",
    description: "A rounded pedestal side table in lacquered ash for a bedside or reading nook.",
    descriptionAr: "طاولة جانبية دائرية بقاعدة من خشب الدردار المطلي لجانب السرير أو ركن القراءة.",
    category: "side-tables",
    price: 44,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 42, depthCm: 42, heightCm: 55, diameterCm: 42 },
    materials: ["ash"],
    colors: ["ivory", "sage", "charcoal"],
    styleTags: ["japandi", "minimal"],
    roomTypes: ["bedroom", "living-room"],
    features: [
      { en: "Rounded pedestal base", ar: "قاعدة دائرية" },
      { en: "Lacquered finish", ar: "تشطيب مطلي" },
    ],
    customizable: false,
  },

  // ── Dining tables ────────────────────────────────────────────────────────
  {
    slug: "tala-dining-table",
    name: "Tala Dining Table",
    nameAr: "طاولة تالا للطعام",
    description: "A six-seat solid-oak dining table with tapered legs and a natural oil finish.",
    descriptionAr: "طاولة طعام لستة أشخاص من خشب البلوط الصلب بأرجل مدببة وتشطيب زيتي طبيعي.",
    category: "dining",
    price: 285,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 180, depthCm: 90, heightCm: 75 },
    materials: ["oak"],
    colors: ["oak", "walnut"],
    styleTags: ["scandinavian", "warm-modern"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Seats six", ar: "تتّسع لستة أشخاص" },
      { en: "Natural oil finish", ar: "تشطيب بالزيت الطبيعي" },
    ],
    customizable: true,
    customizationOptions: ["size", "finish"],
  },
  {
    slug: "nadia-round-dining-table",
    name: "Nadia Round Dining Table",
    nameAr: "طاولة نادية الدائرية للطعام",
    description: "A round four-seat table on a central pedestal — easy to gather around.",
    descriptionAr: "طاولة دائرية لأربعة أشخاص بقاعدة مركزية، يسهل التجمّع حولها.",
    category: "dining",
    price: 235,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 120, depthCm: 120, heightCm: 75, diameterCm: 120 },
    materials: ["ash", "steel"],
    colors: ["ivory", "oak", "charcoal"],
    styleTags: ["contemporary", "minimal"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Central pedestal", ar: "قاعدة مركزية" },
      { en: "Seats four", ar: "تتّسع لأربعة أشخاص" },
    ],
    customizable: false,
  },
  {
    slug: "bilal-extending-dining-table",
    name: "Bilal Extending Dining Table",
    nameAr: "طاولة بلال القابلة للتمديد",
    description: "An extending table that grows from six to eight seats for guests.",
    descriptionAr: "طاولة قابلة للتمديد تتّسع من ستة إلى ثمانية أشخاص للضيوف.",
    category: "dining",
    price: 340,
    supplier: DEMO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 200, depthCm: 95, heightCm: 75 },
    materials: ["walnut", "steel"],
    colors: ["walnut", "charcoal"],
    styleTags: ["modern", "classic-modern"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Extends for guests", ar: "تتمدّد لاستقبال الضيوف" },
      { en: "Seats six to eight", ar: "تتّسع من ستة إلى ثمانية" },
    ],
    customizable: true,
    customizationOptions: ["finish"],
  },
  {
    slug: "salwa-marble-dining-table",
    name: "Salwa Marble Dining Table",
    nameAr: "طاولة سلوى الرخامية للطعام",
    description: "A statement marble-top dining table on a sculptural base.",
    descriptionAr: "طاولة طعام مميزة بسطح رخامي على قاعدة نحتية.",
    category: "dining",
    price: 460,
    supplier: LAB,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 200, depthCm: 100, heightCm: 75 },
    materials: ["marble", "steel"],
    colors: ["white", "cream", "charcoal"],
    styleTags: ["contemporary", "classic-modern"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Natural marble top", ar: "سطح رخامي طبيعي" },
      { en: "Sculptural base", ar: "قاعدة نحتية" },
    ],
    customizable: false,
  },
  {
    slug: "kamal-bistro-table",
    name: "Kamal Bistro Table",
    nameAr: "طاولة كمال الصغيرة",
    description: "A compact two-seat bistro table for a kitchen corner or small apartment.",
    descriptionAr: "طاولة صغيرة لشخصين لركن المطبخ أو الشقة الصغيرة.",
    category: "dining",
    price: 120,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 70, depthCm: 70, heightCm: 74, diameterCm: 70 },
    materials: ["oak", "metal"],
    colors: ["oak", "charcoal", "sage"],
    styleTags: ["scandinavian", "minimal"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Space-saving two-seater", ar: "طاولة موفّرة لشخصين" },
      { en: "Kitchen-corner scale", ar: "بحجم ركن المطبخ" },
    ],
    customizable: false,
  },
  {
    slug: "hessa-console-dining-table",
    name: "Hessa Console Dining Table",
    nameAr: "طاولة حصة الطعام الطويلة",
    description: "A long, narrow dining console with a live-edge oak top for a dining-hall wall.",
    descriptionAr: "طاولة طعام طويلة وضيقة بسطح بلوط طبيعي الحافة لجدار صالة الطعام.",
    category: "dining",
    price: 310,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 220, depthCm: 80, heightCm: 75 },
    materials: ["oak", "steel"],
    colors: ["oak", "walnut", "charcoal"],
    styleTags: ["warm-modern", "industrial"],
    roomTypes: ["dining-room"],
    features: [
      { en: "Live-edge oak top", ar: "سطح بلوط بحافة طبيعية" },
      { en: "Seats up to eight", ar: "تتّسع حتى ثمانية أشخاص" },
    ],
    customizable: true,
    customizationOptions: ["size"],
  },

  // ── Beds ─────────────────────────────────────────────────────────────────
  {
    slug: "layan-upholstered-bed",
    name: "Layan Upholstered Bed",
    nameAr: "سرير ليان المنجّد",
    description: "A king bed with a low upholstered headboard in soft bouclé.",
    descriptionAr: "سرير كينج بلوح رأس منجّد منخفض من قماش البوكليه الناعم.",
    category: "beds",
    subcategory: "king",
    price: 315,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 196, depthCm: 214, heightCm: 100 },
    materials: ["boucle", "oak"],
    colors: ["cream", "beige", "grey"],
    styleTags: ["warm-modern", "contemporary"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Low upholstered headboard", ar: "لوح رأس منجّد منخفض" },
      { en: "Fits a king mattress", ar: "يناسب مرتبة كينج" },
    ],
    customizable: true,
    customizationOptions: ["fabric", "size"],
  },
  {
    slug: "hamad-oak-platform-bed",
    name: "Hamad Oak Platform Bed",
    nameAr: "سرير حمد المنصّة من البلوط",
    description: "A low solid-oak platform bed with an integrated headboard shelf.",
    descriptionAr: "سرير منصّة منخفض من خشب البلوط الصلب مع رف مدمج في لوح الرأس.",
    category: "beds",
    subcategory: "king",
    price: 360,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 200, depthCm: 216, heightCm: 90 },
    materials: ["oak"],
    colors: ["oak", "walnut"],
    styleTags: ["japandi", "minimal"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Integrated headboard shelf", ar: "رف مدمج في لوح الرأس" },
      { en: "Low platform profile", ar: "تصميم منصّة منخفض" },
    ],
    customizable: true,
    customizationOptions: ["size"],
  },
  {
    slug: "rana-queen-bed",
    name: "Rana Queen Bed",
    nameAr: "سرير رنا كوين",
    description: "A queen bed with a curved wing headboard in linen.",
    descriptionAr: "سرير كوين بلوح رأس منحنٍ من الكتان.",
    category: "beds",
    subcategory: "queen",
    price: 275,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 166, depthCm: 210, heightCm: 110 },
    materials: ["linen", "ash"],
    colors: ["beige", "sage", "taupe"],
    styleTags: ["contemporary", "warm-modern"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Curved wing headboard", ar: "لوح رأس منحنٍ بأجنحة" },
      { en: "Fits a queen mattress", ar: "يناسب مرتبة كوين" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "sami-single-bed",
    name: "Sami Single Bed",
    nameAr: "سرير سامي المفرد",
    description: "A simple single bed in oak — ideal for a guest or child's room.",
    descriptionAr: "سرير مفرد بسيط من خشب البلوط، مثالي لغرفة الضيوف أو الأطفال.",
    category: "beds",
    subcategory: "single",
    price: 175,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 106, depthCm: 206, heightCm: 90 },
    materials: ["oak"],
    colors: ["oak", "white", "sage"],
    styleTags: ["scandinavian", "minimal"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Guest & children friendly", ar: "مناسب للضيوف والأطفال" },
      { en: "Slatted base included", ar: "قاعدة شرائح مرفقة" },
    ],
    customizable: false,
  },
  {
    slug: "dima-storage-bed",
    name: "Dima Storage Bed",
    nameAr: "سرير ديما بالتخزين",
    description: "A king bed with a lift-up base for hidden seasonal storage.",
    descriptionAr: "سرير كينج بقاعدة قابلة للرفع لتخزين موسمي مخفي.",
    category: "beds",
    subcategory: "king",
    price: 395,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 198, depthCm: 216, heightCm: 105 },
    materials: ["velvet", "oak"],
    colors: ["grey", "navy", "charcoal"],
    styleTags: ["modern", "contemporary"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Lift-up storage base", ar: "قاعدة تخزين قابلة للرفع" },
      { en: "Upholstered surround", ar: "إطار منجّد" },
    ],
    customizable: true,
    customizationOptions: ["fabric"],
  },
  {
    slug: "hoor-cane-bed",
    name: "Hoor Cane Bed",
    nameAr: "سرير حور بالخيزران",
    description: "A queen bed with a woven-cane headboard for a light, airy bedroom.",
    descriptionAr: "سرير كوين بلوح رأس من الخيزران المنسوج لغرفة نوم خفيفة ومنعشة.",
    category: "beds",
    subcategory: "queen",
    price: 300,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 168, depthCm: 212, heightCm: 112 },
    materials: ["rattan", "ash"],
    colors: ["oak", "cream", "ivory"],
    styleTags: ["boho", "japandi"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Woven-cane headboard", ar: "لوح رأس من الخيزران المنسوج" },
      { en: "Light, airy look", ar: "مظهر خفيف ومنعش" },
    ],
    customizable: false,
  },

  // ── Storage ──────────────────────────────────────────────────────────────
  {
    slug: "faisal-sideboard",
    name: "Faisal Sideboard",
    nameAr: "بوفيه فيصل",
    description: "A long oak sideboard with fluted doors and soft-close storage.",
    descriptionAr: "بوفيه طويل من خشب البلوط بأبواب مضلّعة وتخزين بإغلاق ناعم.",
    category: "storage",
    subcategory: "sideboard",
    price: 245,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 180, depthCm: 45, heightCm: 75 },
    materials: ["oak"],
    colors: ["oak", "walnut", "sage"],
    styleTags: ["warm-modern", "mid-century"],
    roomTypes: ["living-room", "dining-room"],
    features: [
      { en: "Fluted door fronts", ar: "واجهات أبواب مضلّعة" },
      { en: "Soft-close storage", ar: "تخزين بإغلاق ناعم" },
    ],
    customizable: true,
    customizationOptions: ["finish"],
  },
  {
    slug: "amal-bookshelf",
    name: "Amal Bookshelf",
    nameAr: "مكتبة أمل",
    description: "An open five-tier shelving unit in oak and slim steel uprights.",
    descriptionAr: "وحدة رفوف مفتوحة من خمس طبقات من خشب البلوط وأعمدة فولاذية رفيعة.",
    category: "storage",
    subcategory: "shelving",
    price: 180,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 90, depthCm: 35, heightCm: 190 },
    materials: ["oak", "steel"],
    colors: ["oak", "charcoal", "black"],
    styleTags: ["industrial", "minimal"],
    roomTypes: ["living-room", "office"],
    features: [
      { en: "Five open tiers", ar: "خمس طبقات مفتوحة" },
      { en: "Wall-anchor included", ar: "مثبّت جداري مرفق" },
    ],
    customizable: false,
  },
  {
    slug: "khalid-dresser",
    name: "Khalid Dresser",
    nameAr: "خزانة أدراج خالد",
    description: "A six-drawer dresser in warm oak with recessed handles.",
    descriptionAr: "خزانة بستة أدراج من خشب البلوط الدافئ بمقابض غائرة.",
    category: "storage",
    subcategory: "dresser",
    price: 265,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 140, depthCm: 45, heightCm: 80 },
    materials: ["oak"],
    colors: ["oak", "walnut", "white"],
    styleTags: ["scandinavian", "warm-modern"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Six roomy drawers", ar: "ستة أدراج واسعة" },
      { en: "Recessed handles", ar: "مقابض غائرة" },
    ],
    customizable: false,
  },
  {
    slug: "salem-shoe-cabinet",
    name: "Salem Shoe Cabinet",
    nameAr: "خزانة أحذية سالم",
    description: "A slim entryway shoe cabinet with tilting compartments.",
    descriptionAr: "خزانة أحذية رفيعة للمدخل بأقسام مائلة.",
    category: "storage",
    subcategory: "cabinet",
    price: 130,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 80, depthCm: 24, heightCm: 120 },
    materials: ["ash"],
    colors: ["white", "oak", "charcoal"],
    styleTags: ["minimal", "modern"],
    roomTypes: ["entryway"],
    features: [
      { en: "Slim entryway depth", ar: "عمق رفيع مناسب للمدخل" },
      { en: "Tilting shoe bins", ar: "أقسام أحذية مائلة" },
    ],
    customizable: false,
  },
  {
    slug: "budur-cube-storage",
    name: "Budur Cube Storage",
    nameAr: "وحدة بدور المكعّبة للتخزين",
    description: "A modular cube unit with optional fabric bins for living-room clutter.",
    descriptionAr: "وحدة مكعّبات معيارية مع صناديق قماشية اختيارية لترتيب غرفة المعيشة.",
    category: "storage",
    subcategory: "shelving",
    price: 155,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 105, depthCm: 38, heightCm: 105 },
    materials: ["oak", "cotton"],
    colors: ["oak", "beige", "charcoal"],
    styleTags: ["scandinavian", "contemporary"],
    roomTypes: ["living-room", "office"],
    features: [
      { en: "Modular cube layout", ar: "تخطيط مكعّبات معياري" },
      { en: "Optional fabric bins", ar: "صناديق قماشية اختيارية" },
    ],
    customizable: true,
    customizationOptions: ["configuration"],
  },

  // ── Wardrobes ────────────────────────────────────────────────────────────
  {
    slug: "sultan-two-door-wardrobe",
    name: "Sultan Two-Door Wardrobe",
    nameAr: "دولاب سلطان بابين",
    description: "A two-door wardrobe in oak with a full-length rail and upper shelf.",
    descriptionAr: "دولاب ملابس ببابين من خشب البلوط مع قضيب كامل الطول ورف علوي.",
    category: "wardrobes",
    price: 320,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 100, depthCm: 58, heightCm: 200 },
    materials: ["oak"],
    colors: ["oak", "white", "walnut"],
    styleTags: ["scandinavian", "warm-modern"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Full-length hanging rail", ar: "قضيب تعليق كامل الطول" },
      { en: "Adjustable upper shelf", ar: "رف علوي قابل للتعديل" },
    ],
    customizable: true,
    customizationOptions: ["finish", "internal-layout"],
  },
  {
    slug: "aisha-sliding-wardrobe",
    name: "Aisha Sliding Wardrobe",
    nameAr: "دولاب عائشة المنزلق",
    description: "A three-door sliding wardrobe with a soft matte finish and mirror panel.",
    descriptionAr: "دولاب بثلاثة أبواب منزلقة بتشطيب مطفي ناعم ولوح مرآة.",
    category: "wardrobes",
    price: 460,
    supplier: DEMO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 180, depthCm: 62, heightCm: 210 },
    materials: ["ash", "glass"],
    colors: ["white", "grey", "charcoal"],
    styleTags: ["modern", "minimal"],
    roomTypes: ["bedroom"],
    features: [
      { en: "Space-saving sliding doors", ar: "أبواب منزلقة موفّرة للمساحة" },
      { en: "Integrated mirror panel", ar: "لوح مرآة مدمج" },
    ],
    customizable: true,
    customizationOptions: ["finish"],
  },
  {
    slug: "faten-open-wardrobe",
    name: "Faten Open Wardrobe",
    nameAr: "دولاب فاتن المفتوح",
    description: "An open clothing rail with a shelf and drawer for a dressing corner.",
    descriptionAr: "قضيب ملابس مفتوح مع رف ودرج لركن تبديل الملابس.",
    category: "wardrobes",
    price: 165,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 110, depthCm: 45, heightCm: 175 },
    materials: ["oak", "steel"],
    colors: ["oak", "charcoal", "black"],
    styleTags: ["industrial", "minimal"],
    roomTypes: ["bedroom", "entryway"],
    features: [
      { en: "Open hanging rail", ar: "قضيب تعليق مفتوح" },
      { en: "Shelf and drawer", ar: "رف ودرج" },
    ],
    customizable: false,
  },

  // ── TV units ─────────────────────────────────────────────────────────────
  {
    slug: "nasser-tv-console",
    name: "Nasser TV Console",
    nameAr: "طاولة ناصر للتلفزيون",
    description: "A low oak media console with fluted sliding doors and cable routing.",
    descriptionAr: "طاولة تلفزيون منخفضة من خشب البلوط بأبواب منزلقة مضلّعة وتمرير للأسلاك.",
    category: "tv-units",
    price: 210,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 180, depthCm: 40, heightCm: 48 },
    materials: ["oak"],
    colors: ["oak", "walnut", "charcoal"],
    styleTags: ["warm-modern", "mid-century"],
    roomTypes: ["living-room"],
    features: [
      { en: "Fluted sliding doors", ar: "أبواب منزلقة مضلّعة" },
      { en: "Rear cable routing", ar: "تمرير خلفي للأسلاك" },
    ],
    customizable: true,
    customizationOptions: ["finish"],
  },
  {
    slug: "hessa-floating-tv-unit",
    name: "Hessa Floating TV Unit",
    nameAr: "وحدة حصة المعلّقة للتلفزيون",
    description: "A wall-mounted floating media unit that keeps the floor clear.",
    descriptionAr: "وحدة تلفزيون معلّقة على الجدار تُبقي الأرضية خالية.",
    category: "tv-units",
    price: 175,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 150, depthCm: 32, heightCm: 30 },
    materials: ["ash"],
    colors: ["white", "oak", "charcoal"],
    styleTags: ["minimal", "modern"],
    roomTypes: ["living-room"],
    features: [
      { en: "Wall-mounted, floor-free", ar: "معلّقة على الجدار وتحرّر الأرضية" },
      { en: "Push-to-open drawers", ar: "أدراج بفتح بالضغط" },
    ],
    customizable: false,
  },
  {
    slug: "majed-media-cabinet",
    name: "Majed Media Cabinet",
    nameAr: "خزانة ماجد الإعلامية",
    description: "A wider media cabinet with mixed open and closed storage.",
    descriptionAr: "خزانة إعلامية أعرض بمزيج من التخزين المفتوح والمغلق.",
    category: "tv-units",
    price: 245,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 200, depthCm: 42, heightCm: 52 },
    materials: ["walnut", "steel"],
    colors: ["walnut", "charcoal", "sage"],
    styleTags: ["industrial", "contemporary"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Open and closed storage", ar: "تخزين مفتوح ومغلق" },
      { en: "Ventilated media bays", ar: "أقسام أجهزة مهوّاة" },
    ],
    customizable: true,
    customizationOptions: ["finish"],
  },

  // ── Desks ────────────────────────────────────────────────────────────────
  {
    slug: "ziad-writing-desk",
    name: "Ziad Writing Desk",
    nameAr: "مكتب زياد للكتابة",
    description: "A slim oak writing desk with a single drawer and cable notch.",
    descriptionAr: "مكتب كتابة رفيع من خشب البلوط بدرج واحد وفتحة للأسلاك.",
    category: "desks",
    price: 155,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 120, depthCm: 55, heightCm: 75 },
    materials: ["oak", "steel"],
    colors: ["oak", "white", "charcoal"],
    styleTags: ["scandinavian", "minimal"],
    roomTypes: ["office", "bedroom"],
    features: [
      { en: "Single storage drawer", ar: "درج تخزين واحد" },
      { en: "Cable management notch", ar: "فتحة لتنظيم الأسلاك" },
    ],
    customizable: false,
  },
  {
    slug: "maryam-desk",
    name: "Maryam Desk",
    nameAr: "مكتب مريم",
    description: "A generous home-office desk in walnut with a side drawer stack.",
    descriptionAr: "مكتب منزلي واسع من خشب الجوز مع مجموعة أدراج جانبية.",
    category: "desks",
    price: 235,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 150, depthCm: 70, heightCm: 75 },
    materials: ["walnut", "steel"],
    colors: ["walnut", "charcoal", "black"],
    styleTags: ["mid-century", "modern"],
    roomTypes: ["office"],
    features: [
      { en: "Three-drawer stack", ar: "مجموعة من ثلاثة أدراج" },
      { en: "Roomy work surface", ar: "سطح عمل واسع" },
    ],
    customizable: false,
  },
  {
    slug: "tariq-standing-desk",
    name: "Tariq Standing Desk",
    nameAr: "مكتب طارق الواقف",
    description: "A height-adjustable standing desk with an oak top and steel legs.",
    descriptionAr: "مكتب واقف قابل لتعديل الارتفاع بسطح من البلوط وأرجل فولاذية.",
    category: "desks",
    price: 290,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 140, depthCm: 68, heightCm: 120 },
    materials: ["oak", "steel"],
    colors: ["oak", "charcoal", "white"],
    styleTags: ["modern", "industrial"],
    roomTypes: ["office"],
    features: [
      { en: "Height adjustable sit-stand", ar: "قابل لتعديل الارتفاع جلوس ووقوف" },
      { en: "Steady steel legs", ar: "أرجل فولاذية ثابتة" },
    ],
    customizable: false,
  },
  {
    slug: "salma-compact-desk",
    name: "Salma Compact Desk",
    nameAr: "مكتب سلمى المدمج",
    description: "A compact desk for small rooms with an integrated shelf.",
    descriptionAr: "مكتب مدمج للغرف الصغيرة مع رف مدمج.",
    category: "desks",
    price: 120,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 100, depthCm: 50, heightCm: 90 },
    materials: ["ash"],
    colors: ["white", "oak", "sage"],
    styleTags: ["minimal", "scandinavian"],
    roomTypes: ["office", "bedroom"],
    features: [
      { en: "Integrated upper shelf", ar: "رف علوي مدمج" },
      { en: "Small-room footprint", ar: "مساحة مناسبة للغرف الصغيرة" },
    ],
    customizable: false,
  },

  // ── Rugs ─────────────────────────────────────────────────────────────────
  {
    slug: "textured-wool-rug",
    name: "Sana Textured Wool Rug",
    nameAr: "سجادة سنا الصوفية المزخرفة",
    description: "A hand-loomed wool-blend rug with a low, tonal texture — 200 × 290 cm.",
    descriptionAr: "سجادة من مزيج الصوف منسوجة يدوياً بملمس منخفض ومتدرّج — 200 × 290 سم.",
    category: "rugs",
    price: 58,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 200, depthCm: 290, heightCm: 1 },
    materials: ["wool", "cotton"],
    colors: ["beige", "sand", "ivory"],
    styleTags: ["warm-modern", "japandi"],
    roomTypes: ["living-room", "bedroom", "majlis"],
    features: [
      { en: "Hand-loomed wool blend", ar: "مزيج صوف منسوج يدوياً" },
      { en: "Low tonal texture", ar: "ملمس متدرّج منخفض" },
    ],
    customizable: false,
  },
  {
    slug: "hessa-berber-rug",
    name: "Hessa Berber Rug",
    nameAr: "سجادة حصة البربرية",
    description: "A soft, high-pile Berber-style rug with a subtle diamond motif — 160 × 230 cm.",
    descriptionAr: "سجادة ناعمة بوبر عالٍ بطراز بربري مع نقش معيّن خفيف — 160 × 230 سم.",
    category: "rugs",
    price: 66,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 160, depthCm: 230, heightCm: 2 },
    materials: ["wool"],
    colors: ["ivory", "cream", "charcoal"],
    styleTags: ["boho", "scandinavian"],
    roomTypes: ["living-room", "bedroom"],
    features: [
      { en: "Soft high pile", ar: "وبر عالٍ ناعم" },
      { en: "Subtle diamond motif", ar: "نقش معيّن خفيف" },
    ],
    customizable: false,
  },
  {
    slug: "nada-flatweave-rug",
    name: "Nada Flatweave Rug",
    nameAr: "سجادة ندى المسطّحة",
    description: "A durable flatweave rug that suits high-traffic living rooms — 170 × 240 cm.",
    descriptionAr: "سجادة مسطّحة متينة تناسب غرف المعيشة كثيرة الاستخدام — 170 × 240 سم.",
    category: "rugs",
    price: 44,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 170, depthCm: 240, heightCm: 1 },
    materials: ["cotton", "wool"],
    colors: ["sage", "taupe", "grey"],
    styleTags: ["contemporary", "minimal"],
    roomTypes: ["living-room", "dining-room"],
    features: [
      { en: "Durable flatweave", ar: "نسيج مسطّح متين" },
      { en: "Reversible design", ar: "تصميم قابل للعكس" },
    ],
    customizable: false,
  },
  {
    slug: "reem-round-rug",
    name: "Reem Round Rug",
    nameAr: "سجادة ريم الدائرية",
    description: "A round wool rug that softens a reading nook or bedside — 200 cm diameter.",
    descriptionAr: "سجادة دائرية من الصوف تُضفي نعومة على ركن القراءة أو جانب السرير — قطر 200 سم.",
    category: "rugs",
    price: 52,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 200, depthCm: 200, heightCm: 2, diameterCm: 200 },
    materials: ["wool"],
    colors: ["cream", "sand", "sage"],
    styleTags: ["japandi", "boho"],
    roomTypes: ["bedroom", "living-room"],
    features: [
      { en: "Round 200 cm form", ar: "شكل دائري 200 سم" },
      { en: "Soft underfoot", ar: "ناعمة تحت الأقدام" },
    ],
    customizable: false,
  },
  {
    slug: "dana-runner-rug",
    name: "Dana Runner Rug",
    nameAr: "سجادة دانة الممرّية",
    description: "A long hallway runner with a fine geometric border — 80 × 300 cm.",
    descriptionAr: "سجادة ممر طويلة بحدود هندسية دقيقة — 80 × 300 سم.",
    category: "rugs",
    price: 36,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 80, depthCm: 300, heightCm: 1 },
    materials: ["cotton"],
    colors: ["charcoal", "taupe", "rust"],
    styleTags: ["contemporary", "boho"],
    roomTypes: ["entryway", "living-room"],
    features: [
      { en: "Hallway runner length", ar: "بطول ممرّي" },
      { en: "Fine geometric border", ar: "حدود هندسية دقيقة" },
    ],
    customizable: false,
  },
  {
    slug: "yara-jute-rug",
    name: "Yara Jute Rug",
    nameAr: "سجادة يارا من الجوت",
    description: "A natural jute rug that layers beautifully under a softer rug — 160 × 230 cm.",
    descriptionAr: "سجادة طبيعية من الجوت تتناسق بجمال تحت سجادة أنعم — 160 × 230 سم.",
    category: "rugs",
    price: 40,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 160, depthCm: 230, heightCm: 1 },
    materials: ["cotton"],
    colors: ["sand", "beige", "taupe"],
    styleTags: ["boho", "japandi"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Natural jute fibre", ar: "ألياف جوت طبيعية" },
      { en: "Layer-friendly base", ar: "أساس مناسب للتنسيق الطبقي" },
    ],
    customizable: false,
  },

  // ── Lighting ─────────────────────────────────────────────────────────────
  {
    slug: "faris-floor-lamp",
    name: "Faris Floor Lamp",
    nameAr: "مصباح فارس الأرضي",
    description: "An arc floor lamp in brushed brass with a linen shade — 150 cm.",
    descriptionAr: "مصباح أرضي مقوّس من النحاس المصقول بغطاء كتان — 150 سم.",
    category: "lighting",
    subcategory: "floor",
    price: 42,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 40, depthCm: 40, heightCm: 150 },
    materials: ["brass", "linen"],
    colors: ["brass", "ivory", "charcoal"],
    styleTags: ["mid-century", "warm-modern"],
    roomTypes: ["living-room", "majlis", "office"],
    features: [
      { en: "Arc reach over a sofa", ar: "ذراع مقوّس فوق الكنبة" },
      { en: "Warm linen shade", ar: "غطاء كتان دافئ" },
    ],
    customizable: false,
  },
  {
    slug: "sena-table-lamp",
    name: "Sena Table Lamp",
    nameAr: "مصباح سِنا للطاولة",
    description: "A ceramic table lamp with a soft-glow linen shade for a bedside.",
    descriptionAr: "مصباح طاولة من السيراميك بغطاء كتان بإضاءة ناعمة لجانب السرير.",
    category: "lighting",
    subcategory: "table",
    price: 28,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 28, depthCm: 28, heightCm: 46 },
    materials: ["ceramic", "linen"],
    colors: ["sand", "sage", "ivory"],
    styleTags: ["japandi", "contemporary"],
    roomTypes: ["bedroom", "living-room"],
    features: [
      { en: "Ceramic body", ar: "جسم من السيراميك" },
      { en: "Soft-glow shade", ar: "غطاء بإضاءة ناعمة" },
    ],
    customizable: false,
  },
  {
    slug: "malak-pendant-light",
    name: "Malak Pendant Light",
    nameAr: "معلّقة ملاك للإضاءة",
    description: "A woven-rattan pendant that casts a warm, patterned glow over a table.",
    descriptionAr: "معلّقة من الخيزران المنسوج تنشر إضاءة دافئة مزخرفة فوق الطاولة.",
    category: "lighting",
    subcategory: "pendant",
    price: 48,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 45, depthCm: 45, heightCm: 40, diameterCm: 45 },
    materials: ["rattan"],
    colors: ["oak", "sand", "cream"],
    styleTags: ["boho", "japandi"],
    roomTypes: ["dining-room", "living-room"],
    features: [
      { en: "Woven rattan shade", ar: "غطاء من الخيزران المنسوج" },
      { en: "Patterned warm glow", ar: "إضاءة دافئة مزخرفة" },
    ],
    customizable: false,
  },
  {
    slug: "adam-linear-pendant",
    name: "Adam Linear Pendant",
    nameAr: "معلّقة آدم الخطية",
    description: "A long linear pendant in matte black for over a dining table.",
    descriptionAr: "معلّقة خطية طويلة باللون الأسود المطفي فوق طاولة الطعام.",
    category: "lighting",
    subcategory: "pendant",
    price: 64,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 90, depthCm: 12, heightCm: 20 },
    materials: ["metal", "steel"],
    colors: ["black", "charcoal", "brass"],
    styleTags: ["industrial", "modern"],
    roomTypes: ["dining-room", "office"],
    features: [
      { en: "Linear dining light", ar: "إضاءة خطية للطعام" },
      { en: "Dimmable module", ar: "وحدة قابلة للتعتيم" },
    ],
    customizable: false,
  },
  {
    slug: "lulu-wall-sconce",
    name: "Lulu Wall Sconce",
    nameAr: "إضاءة لولو الجدارية",
    description: "A small brass wall sconce for a hallway or bedside reading light.",
    descriptionAr: "إضاءة جدارية صغيرة من النحاس للممر أو القراءة بجانب السرير.",
    category: "lighting",
    subcategory: "wall",
    price: 32,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 12, depthCm: 18, heightCm: 30 },
    materials: ["brass"],
    colors: ["brass", "black", "ivory"],
    styleTags: ["classic-modern", "mid-century"],
    roomTypes: ["bedroom", "entryway"],
    features: [
      { en: "Adjustable reading arm", ar: "ذراع قراءة قابل للتعديل" },
      { en: "Hardwired or plug-in", ar: "توصيل مباشر أو بقابس" },
    ],
    customizable: false,
  },
  {
    slug: "nawaf-tripod-lamp",
    name: "Nawaf Tripod Floor Lamp",
    nameAr: "مصباح نواف ثلاثي القوائم",
    description: "A tripod floor lamp in oak legs with a wide drum shade.",
    descriptionAr: "مصباح أرضي بقوائم ثلاثية من خشب البلوط وغطاء أسطواني عريض.",
    category: "lighting",
    subcategory: "floor",
    price: 46,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 50, depthCm: 50, heightCm: 155 },
    materials: ["oak", "linen"],
    colors: ["oak", "ivory", "charcoal"],
    styleTags: ["scandinavian", "mid-century"],
    roomTypes: ["living-room", "office"],
    features: [
      { en: "Oak tripod legs", ar: "قوائم ثلاثية من البلوط" },
      { en: "Wide drum shade", ar: "غطاء أسطواني عريض" },
    ],
    customizable: false,
  },

  // ── Mirrors ──────────────────────────────────────────────────────────────
  {
    slug: "lamar-arch-mirror",
    name: "Lamar Arch Mirror",
    nameAr: "مرآة لمار المقوّسة",
    description: "A full-length arched mirror with a slim oak frame for an entryway.",
    descriptionAr: "مرآة كاملة الطول مقوّسة بإطار رفيع من خشب البلوط للمدخل.",
    category: "mirrors",
    price: 88,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 70, depthCm: 3, heightCm: 170 },
    materials: ["oak", "glass"],
    colors: ["oak", "black", "brass"],
    styleTags: ["contemporary", "warm-modern"],
    roomTypes: ["entryway", "bedroom"],
    features: [
      { en: "Full-length arch", ar: "قوس كامل الطول" },
      { en: "Slim oak frame", ar: "إطار رفيع من البلوط" },
    ],
    customizable: false,
  },
  {
    slug: "sundus-round-mirror",
    name: "Sundus Round Mirror",
    nameAr: "مرآة سندس الدائرية",
    description: "A round brass-framed mirror that brightens a hallway or above a console.",
    descriptionAr: "مرآة دائرية بإطار نحاسي تضيء الممر أو فوق الكونسول.",
    category: "mirrors",
    price: 54,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 80, depthCm: 3, heightCm: 80, diameterCm: 80 },
    materials: ["brass", "glass"],
    colors: ["brass", "black", "charcoal"],
    styleTags: ["classic-modern", "mid-century"],
    roomTypes: ["entryway", "living-room"],
    features: [
      { en: "Round brass frame", ar: "إطار نحاسي دائري" },
      { en: "Brightens the room", ar: "يضيء الغرفة" },
    ],
    customizable: false,
  },
  {
    slug: "maya-leaner-mirror",
    name: "Maya Leaner Mirror",
    nameAr: "مرآة مايا المتّكئة",
    description: "An oversized leaning mirror that adds depth to a bedroom wall.",
    descriptionAr: "مرآة كبيرة متّكئة تضيف عمقاً لجدار غرفة النوم.",
    category: "mirrors",
    price: 96,
    supplier: LAB,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 90, depthCm: 4, heightCm: 180 },
    materials: ["ash", "glass"],
    colors: ["white", "oak", "charcoal"],
    styleTags: ["minimal", "modern"],
    roomTypes: ["bedroom", "living-room"],
    features: [
      { en: "Oversized leaning form", ar: "شكل كبير متّكئ" },
      { en: "Adds visual depth", ar: "يضيف عمقاً بصرياً" },
    ],
    customizable: false,
  },

  // ── Decor ────────────────────────────────────────────────────────────────
  {
    slug: "salma-ceramic-vase",
    name: "Salma Ceramic Vase Set",
    nameAr: "طقم مزهريات سلمى الخزفية",
    description: "A set of three matte ceramic vases in graduated heights.",
    descriptionAr: "طقم من ثلاث مزهريات خزفية مطفية بارتفاعات متدرّجة.",
    category: "decor",
    subcategory: "vase",
    price: 24,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 15, depthCm: 15, heightCm: 30 },
    materials: ["ceramic"],
    colors: ["sand", "sage", "ivory"],
    styleTags: ["japandi", "minimal"],
    roomTypes: ["living-room", "dining-room"],
    features: [
      { en: "Set of three", ar: "طقم من ثلاث قطع" },
      { en: "Matte ceramic finish", ar: "تشطيب خزفي مطفي" },
    ],
    customizable: false,
  },
  {
    slug: "rima-throw-blanket",
    name: "Rima Wool Throw",
    nameAr: "بطانية ريما الصوفية",
    description: "A chunky-knit wool throw to layer over a sofa or bed.",
    descriptionAr: "بطانية صوفية بحياكة سميكة للتنسيق فوق الكنبة أو السرير.",
    category: "decor",
    subcategory: "textile",
    price: 22,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 130, depthCm: 170, heightCm: 2 },
    materials: ["wool"],
    colors: ["cream", "sage", "rust"],
    styleTags: ["boho", "scandinavian"],
    roomTypes: ["living-room", "bedroom", "majlis"],
    features: [
      { en: "Chunky-knit wool", ar: "صوف بحياكة سميكة" },
      { en: "Sofa or bed layer", ar: "طبقة للكنبة أو السرير" },
    ],
    customizable: false,
  },
  {
    slug: "noor-cushion-set",
    name: "Noor Cushion Set",
    nameAr: "طقم وسائد نور",
    description: "A pair of linen cushions with a subtle tonal weave — covers only.",
    descriptionAr: "زوج من وسائد الكتان بنسيج متدرّج خفيف — أغطية فقط.",
    category: "decor",
    subcategory: "textile",
    price: 18,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 50, depthCm: 50, heightCm: 12 },
    materials: ["linen"],
    colors: ["beige", "olive", "terracotta"],
    styleTags: ["warm-modern", "japandi"],
    roomTypes: ["living-room", "majlis", "bedroom"],
    features: [
      { en: "Pair of covers", ar: "زوج من الأغطية" },
      { en: "Hidden zip closure", ar: "سحّاب مخفي" },
    ],
    customizable: false,
  },
  {
    slug: "aseel-wall-art",
    name: "Aseel Framed Wall Art",
    nameAr: "لوحة أسيل المؤطّرة",
    description: "A set of two abstract framed prints in warm, earthy tones.",
    descriptionAr: "طقم من لوحتين مطبوعتين مجرّدتين بألوان ترابية دافئة.",
    category: "decor",
    subcategory: "wall-art",
    price: 30,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 50, depthCm: 2, heightCm: 70 },
    materials: ["oak", "glass"],
    colors: ["sand", "rust", "charcoal"],
    styleTags: ["boho", "contemporary"],
    roomTypes: ["living-room", "bedroom", "office"],
    features: [
      { en: "Set of two prints", ar: "طقم من مطبوعتين" },
      { en: "Warm earthy palette", ar: "ألوان ترابية دافئة" },
    ],
    customizable: false,
  },
  {
    slug: "dala-table-tray",
    name: "Dala Wooden Tray",
    nameAr: "صينية دلة الخشبية",
    description: "A round walnut serving tray for a coffee table or majlis.",
    descriptionAr: "صينية تقديم دائرية من خشب الجوز لطاولة القهوة أو المجلس.",
    category: "decor",
    subcategory: "object",
    price: 16,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 40, depthCm: 40, heightCm: 5, diameterCm: 40 },
    materials: ["walnut"],
    colors: ["walnut", "oak"],
    styleTags: ["warm-modern", "classic-modern"],
    roomTypes: ["living-room", "majlis"],
    features: [
      { en: "Round walnut form", ar: "شكل دائري من الجوز" },
      { en: "Carry handles", ar: "مقابض للحمل" },
    ],
    customizable: false,
  },

  // ── Outdoor ──────────────────────────────────────────────────────────────
  {
    slug: "bahr-outdoor-sofa",
    name: "Bahr Outdoor Sofa",
    nameAr: "كنبة بحر الخارجية",
    description: "A weather-resistant two-seat outdoor sofa in teak with quick-dry cushions.",
    descriptionAr: "كنبة خارجية لمقعدين مقاومة للأجواء من خشب الساج بوسائد سريعة الجفاف.",
    category: "outdoor",
    subcategory: "seating",
    price: 265,
    supplier: STUDIO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 150, depthCm: 82, heightCm: 74, seatHeightCm: 42 },
    materials: ["teak", "cotton"],
    colors: ["oak", "sand", "olive"],
    styleTags: ["contemporary", "scandinavian"],
    roomTypes: ["outdoor"],
    features: [
      { en: "Weather-resistant teak", ar: "خشب ساج مقاوم للأجواء" },
      { en: "Quick-dry cushions", ar: "وسائد سريعة الجفاف" },
    ],
    customizable: false,
  },
  {
    slug: "rimal-outdoor-chair",
    name: "Rimal Outdoor Chair",
    nameAr: "كرسي رمال الخارجي",
    description: "A stackable outdoor lounge chair in powder-coated aluminium and rope.",
    descriptionAr: "كرسي استرخاء خارجي قابل للتكديس من الألمنيوم المطلي والحبل.",
    category: "outdoor",
    subcategory: "seating",
    price: 110,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 66, depthCm: 72, heightCm: 80, seatHeightCm: 40 },
    materials: ["metal", "cotton"],
    colors: ["charcoal", "sand", "olive"],
    styleTags: ["modern", "minimal"],
    roomTypes: ["outdoor"],
    features: [
      { en: "Stackable frame", ar: "هيكل قابل للتكديس" },
      { en: "Woven rope seat", ar: "مقعد من الحبل المنسوج" },
    ],
    customizable: false,
  },
  {
    slug: "waha-outdoor-table",
    name: "Waha Outdoor Table",
    nameAr: "طاولة واحة الخارجية",
    description: "A teak dining table for the terrace, seating four to six.",
    descriptionAr: "طاولة طعام من خشب الساج للتراس تتّسع لأربعة إلى ستة أشخاص.",
    category: "outdoor",
    subcategory: "table",
    price: 235,
    supplier: STUDIO,
    stockStatus: "made-to-order",
    dimensions: { widthCm: 160, depthCm: 90, heightCm: 74 },
    materials: ["teak"],
    colors: ["oak", "walnut"],
    styleTags: ["scandinavian", "contemporary"],
    roomTypes: ["outdoor"],
    features: [
      { en: "Solid teak for outdoors", ar: "خشب ساج صلب للخارج" },
      { en: "Seats four to six", ar: "تتّسع من أربعة إلى ستة" },
    ],
    customizable: false,
  },
  {
    slug: "nakheel-lounger",
    name: "Nakheel Sun Lounger",
    nameAr: "كرسي نخيل للتشمّس",
    description: "An adjustable sun lounger in teak with a quick-dry cushion.",
    descriptionAr: "كرسي تشمّس قابل للتعديل من خشب الساج بوسادة سريعة الجفاف.",
    category: "outdoor",
    subcategory: "seating",
    price: 150,
    supplier: LAB,
    stockStatus: "in-stock",
    dimensions: { widthCm: 68, depthCm: 195, heightCm: 35 },
    materials: ["teak", "cotton"],
    colors: ["oak", "sand", "charcoal"],
    styleTags: ["minimal", "contemporary"],
    roomTypes: ["outdoor"],
    features: [
      { en: "Multi-position recline", ar: "استلقاء متعدّد الأوضاع" },
      { en: "Quick-dry cushion", ar: "وسادة سريعة الجفاف" },
    ],
    customizable: false,
  },
  {
    slug: "faya-planter-set",
    name: "Faya Planter Set",
    nameAr: "طقم أحواض فايا",
    description: "A set of two frost-safe outdoor planters in matte stone finish.",
    descriptionAr: "طقم من حوضي زرع خارجيين مقاومين للبرد بتشطيب حجري مطفي.",
    category: "outdoor",
    subcategory: "decor",
    price: 60,
    supplier: DEMO,
    stockStatus: "in-stock",
    dimensions: { widthCm: 40, depthCm: 40, heightCm: 45 },
    materials: ["stone", "ceramic"],
    colors: ["sand", "charcoal", "taupe"],
    styleTags: ["minimal", "contemporary"],
    roomTypes: ["outdoor", "entryway"],
    features: [
      { en: "Set of two planters", ar: "طقم من حوضين" },
      { en: "Frost-safe finish", ar: "تشطيب مقاوم للبرد" },
    ],
    customizable: false,
  },
];

/** The full, frozen demo catalog. */
export const products: readonly Product[] = Object.freeze(build(rows));
